### ISSUE TITLE
UAT #5 - Stint Risk Issue

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#27] opened 2021-07-05 07:29 UTC
"When entering race setup there is no guidance info for the stint risk limits, also any number can be entered there."

The guidance should say (on hover, if possible) "Enter a number between 1 and 5 - the higher the number the faster you will go, but the more risk of crashing there will be" and inputs that are not a) integers and b) are not between 1 and 5 should not be allowed.

**Comment by christopherh0rn** [comment] 2021-07-06 20:14
The guidance I'm going to put as a duplicate of #31 

The stint risk is already validated:
<img width="717" alt="Screenshot 2021-07-06 at 21 12 36" src="https://user-images.githubusercontent.com/13766234/124661223-1fd2b100-de9f-11eb-82b8-ffab14c44d43.png">
<img width="695" alt="Screenshot 2021-07-06 at 21 12 51" src="https://user-images.githubusercontent.com/13766234/124661230-2103de00-de9f-11eb-81e0-6ee43a1cf6cb.png">

**Closed by christopherh0rn** 2021-07-06 20:14 UTC
Labels: UAT, bug
