### ISSUE TITLE
UAT #6 - Race Setup Inputs Issue

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#28] opened 2021-07-05 07:32 UTC
"No limit to Lap Number when entering stints so you can for instance enter a stop on lap 120 when it is a 100 lap race, any fuel amount can be entered e.g. 1000 ltrs."

Valid point - lap number choices in the race setup screen need to be maxed out at the total number of laps.  That is also the screen where the lap numbers total will need to be shown moving forwards...

Fuel should be maxed at 250 (minimum 10) and again on hover, it would be great to give that feedback to the players.

**Comment by christopherh0rn** [comment] 2021-07-06 20:01
Tooltips request moved to #31 
Lap number request duplicate of #24

**Comment by JonBeagles** [comment] 2021-07-06 21:30
You've said that it's a duplicate of #24?  But it's not...#24 is asking to show how many laps there are in the race.  This request is to limit the amount of laps for a pit-stop the driver can enter...?

**Comment by christopherh0rn** [comment] 2021-07-06 21:36
They both rely on the same underlying information of knowing how many laps that the future race a qualifying session will relate to is going to have. Duplicate might be a bit strong, let's go with very strongly related.

I've currently set a place holder of the maximum lap number to 100 just as a temporary stop gap until the related issue is sorted.

**Closed** 2021-07-07 22:10 UTC
Labels: UAT, bug
